const skills = {
    A: ["Astrology",
        "Acroyoga",
        "Acting",
        "Animation",
        "Automobile Maintenance",
        "Ant-Keeping",
        "Axe Throwing",
        "Art Collecting",
        "Archery",
        "Astronomy",
        "Antiquing",
        "Airsoft",
        "Adult Sport Leagues",
        "ATVing"],
    B: [
        "Board Games",
        "Bouldering",
        "Badminton",
        "Backpacking",
        "Barbecuing",
        "Bass Guitar",
        "Banjo",
        "Boxing",
        "Bodybuilding",
        "Bonsai",
        "Bocce Ball",
        "Baking",
        "Basketball",
        "BASE Jumping",
        "Blogging",
        "Bowling",
        "Bread Making",
        "Breakdancing",
        "Billiards",
        "Bingo",
        "Bushcraft",
        "Beach-combing",
        "Beekeeping",
        "Birdwatching",
        "Beat Making",
        "Beatboxing"
    ],
    C: [
        "Calligraphy",
        "Candle Making",
        "Canoeing",
        "Canyoneering",
        "Cardistry",
        "Caving",
        "Chess",
        "Cheese Making",
        "Coding",
        "Coffee",
        "Coloring",
        "Collage",
        "Collecting",
        "Comic Books",
        "Computer Programming",
        "Composting",
        "Cookouts",
        "Cosplay",
        "Couponing",
        "Crafting",
        "Credit Card Churning",
        "Crocheting",
        "Cross - Stitch",
        "Cross - Word Puzzles",
        "Cycling",
        "Camping",
    ],
    D: [
        "Dancing",
        "Drawing",
        "Darts",
        "Disc Golf",
        "Diorama Making",
        "Diabolo",
        "DJing",
        "Dog Training",
        "Dominoes",
        "Drone Flying",
        "Drums",
    ],
    E: [
        "Equestrianism",
        "Embroidery",
        "Engraving",
        "Exercise",
    ],
    F: [
        "Fantasy Sports",
        "Falconry",
        "Fat Tire Biking",
        "Fish Keeping",
        "Fishing",
        "Fly Tying",
        "Flying Model Planes",
        "Furniture Building",
        "Foraging",
        "Foil Surfing",
        "Filmmaking",
        "Fencing",
    ],
    G: [
        "Gaming",
        "Genealogy",
        "Geocaching",
        "Gardening",
        "Glass Blowing",
        "Graphic Design",
        "Gymnastics",
        "Graffiti",
        "Golf",
        "Guitar",
    ],
    H: [
        "Hacky Sack",
        "Hula Hooping",
        "Hacking",
        "Hang Gliding",
        "Harmonica",
        "Handball",
        "Hammocking",
        "Homebrewing",
        "Heliskiing",
        "Hobby Horsing",
        "Hydroponics",
        "Hiking",
        "Hunting",
        "Horseshoes",
        "Hockey",
    ],
    I: [
        "Ice Skating",
        "Inventing",
        "Ice Fishing",
        "Illustration",
    ],
    J: [
        "Jigsaw Puzzles",
        "Journaling",
        "Juggling",
        "Jaw Harp",
        "Jewelry Making",
        "Jet Skiing",
        "Jump Roping",
        "Jujitsu",
        "Judo",
    ],
    K: [
        "Karaoke",
        "Karate",
        "Kendama",
        "Knife Making",
        "Knitting",
        "Knot Tying",
        "Kombucha Brewing",
        "Kayaking",
        "Kubb",
        "Kickboxing",
        "Korfball",
        "Kite Flying",
        "Kite Surfing",
    ],
    L: [
        "Lapidary",
        "Lacrosse",
        "Landboarding",
        "Languages",
        "Latte Art",
        "Leather Crafting",
        "Lego Building",
        "Lock Picking",
        "LARPing",
        "Long Boarding",
    ],
    M: [
        "Magic Tricks",
        "Magic the Gathering",
        "Macrame",
        "Marathon Running",
        "Martial Arts",
        "Make - Up",
        "Meditation",
        "Metal Detecting",
        "Memory Training",
        "Meteorology",
        "Metaverse",
        "Mindfulness",
        "Mixology",
        "Museum Visiting",
        "Model Building",
        "Model Airplanes",
        "Mölkky",
        "Motorcycles",
        "Mountain Biking",
        "Mountaineering",
        "Mushroom Hunting",
        "Music Production",
    ],
    N: [
        "Needle Point",
        "Nail Art",
        "Noodling",
        "NFT’s",
    ],
    O: [
        "Origami",
        "Off - Roading",
        "Orienteering",
        "Online Games",
        "Opera",
        "Organizing",
    ],
    P: [
        "Painting",
        "Pepakura",
        "Photography",
        "Photoshop",
        "Pen Pals",
        "Peak Bagging",
        "Poetry",
        "Pottery",
        "Puppetry",
        "Pilates",
        "Pole Dancing",
        "Pyrography",
        "Paintball",
        "Parkour",
        "Paragliding",
        "Poker",
        "Power Lifting",
        "Pickle Ball",
    ],
    Q: [
        "Quad Biking",
        "Quilting",
        "Quilling",
        "Quoits",
    ],
    R: [
        "Rapping",
        "Reading",
        "Record Collecting",
        "Refurbishing Furniture",
        "Remote Control Cars",
        "Robotics",
        "Rowing",
        "Rafting",
        "Rappeling",
        "Rock Climbing",
        "Roller Skating",
        "Rugby",
        "Running",
        "Racquetball",
        "Roller Derby",
    ],
    S: [
        "Scrapbooking",
        "Saxophone",
        "Sailing",
        "Sand Art",
        "Scuba Diving",
        "Scootering",
        "Sculpting",
        "Sewing",
        "Singing",
        "Soapmaking",
        "Songwriting",
        "Stand - Up Comedy",
        "Storytelling",
        "Stargazing",
        "Sudoku",
        "Swimming",
        "Shooting",
        "Skateboarding",
        "Skiing",
        "Skimboarding",
        "Skydiving",
        "Slacklining",
        "Sled Dog Racing",
        "Sledding",
        "Sneaker Trading",
        "Stockcar Racing",
        "Sprouting",
        "Stone Skipping",
        "Snowboarding",
        "Snowmobiling",
        "Snowshoeing",
        "Surfing",
    ],
    T: [
        "Table Tennis",
        "Tap Dancing",
        "Tattooing",
        "Taxidermy",
        "Taekwondo",
        "Thrifting",
        "Topiary",
        "Tennis",
        "Teqball",
        "Terrariums",
        "Travel",
        "Trampolining",
        "Tree Climbing",
        "Trivia Nights",
        "Tai Chi",
        "Triathlons",
        "Trail Running",
        "Trap Shooting",
        "Trainspotting",
    ],
    U: [

        "Upcycling",
        "Unicycling",
        "Urban Hiking",
        "Ultimate Frisbee",
    ],
    V: [
        "Video Games",
        "Video Editing",
        "Virtual Reality",
        "Videography",
        "Via Ferratta",
        "Volunteering",
        "Volleyball",
    ],
    W: [
        "Watching Documentaries",
        "Waboba",
        "Watercolor Painting",
        "Water Skiing",
        "Weaving",
        "Web Development",
        "Weight Training",
        "Welding",
        "Whittling",
        "Whale Watching",
        "Wine Making",
        "Wind Surfing",
        "Woodworking",
        "Walking",
        "Word Search Puzzles",
        "Writing",

    ],
    X: [
        "Xylophone",

    ],
    Y: [
        "Yard Games",
        "Yo - yoing",
        "Yoga",
        "Yodeling",
    ],
    Z: [
        "Zumba",
        "Zip Lining",
        "Zentangles",
        "Zorbing",
    ]
}

export default skills;